ARG NODE_BUILD_IMAGE=node:16.20.1-bullseye
FROM $NODE_BUILD_IMAGE AS build

WORKDIR /kerberos
COPY . .

RUN npm run install:kerberos
RUN npm run test

FROM scratch

COPY --from=build /kerberos/prebuilds/