ARG NODE_BUILD_IMAGE=node:16.20.1-bullseye
FROM $NODE_BUILD_IMAGE AS build

WORKDIR /kerberos
COPY . .

RUN npm install -g npm@latest
RUN npm clean-install --ignore-scripts
RUN aptitude install krb5-user
RUN npm run test

FROM scratch

COPY --from=build /kerberos/prebuilds/ /