name: Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Use Node.js LTS
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 'lts/*'

    - name: "Install dependencies"
      shell: bash
      run: |
        npm install --ignore-scripts

    - name: "Install dependencies in the Webpack bundle test package"
      shell: bash
      working-directory: ./test/bundling/webpack
      run: |
        npm install

    - name: "Install local kerberos into Webpack bundle test package"
      shell: bash
      working-directory: ./test/bundling/webpack
      run: |
        npm run install:kerberos

    - name: "Run webpack build"
      shell: bash
      working-directory: ./test/bundling/webpack
      run: |
        npm run build

    - name: "Run bundled script"
      shell: bash
      working-directory: ./test/bundling/webpack
      run: |
        node dist/main.js
